[package]
name = "app"
version = "0.1.0"
edition = "2024"

[dependencies]
serialize_macro = { version = "0.1.0", path = "../serialize_macro" }
serialize_macro_traits = { version = "0.1.0", path = "../serialize_macro_traits" }
